export const TRACK_SERVICE_TOKEN = 'TRACK_SERVICE_TOKEN';
export const COMMENT_SERVICE_TOKEN = 'COMMENT_SERVICE_TOKEN';
export const FILE_SERVICE_TOKEN = 'FILE_SERVICE_TOKEN';

export const COMMENT_REPOSITORY_TOKEN = 'COMMENT_REPOSITORY_TOKEN';
